services:
  openvpn-mngr:
    image: sugoi13/openvpn-mngr
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - /openvpn-mngr/data:/usr/src/app/data
    restart: unless-stopped